MODEL:
  META_ARCHITECTURE: AttrBaseline

  BACKBONE:
    NAME: build_resnet_backbone
    NORM: BN
    DEPTH: 18x
    LAST_STRIDE: 2
    FEAT_DIM: 512
    WITH_IBN: False
    PRETRAIN: True
    PRETRAIN_PATH: /mnt/home/person_att/fast-reid-master/projects/QualityData/weights/resnet18-5c106cde.pth

  HEADS:
    NAME: AttrHead
    WITH_BNNECK: True
    POOL_LAYER: FastGlobalAvgPool
    CLS_LAYER: Linear
    NUM_CLASSES: 2

  LOSSES:
    NAME: ("SoftmaxCrossEntropyLoss",)

    BCE:
      WEIGHT_ENABLED: True
      SCALE: 1.

INPUT:
  SIZE_TRAIN: [ 256, 192]
  SIZE_TEST: [ 256, 192 ]

  FLIP:
    ENABLED: True

  PADDING:
    ENABLED: False

DATALOADER:
  SAMPLER_TRAIN: TrainingSampler
  NUM_WORKERS: 8

SOLVER:
  MAX_EPOCH: 100
  OPT: SGD
  BASE_LR: 0.04
  BIAS_LR_FACTOR: 2.
  HEADS_LR_FACTOR: 10.
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  IMS_PER_BATCH: 256

  NESTEROV: False
  SCHED: CosineAnnealingLR
  # STEPS: [15,20,25,30,35]

  WARMUP_FACTOR: 0.1
  WARMUP_ITERS: 1000

  CHECKPOINT_PERIOD: 5

TEST:
  EVAL_PERIOD: 5
  IMS_PER_BATCH: 256

CUDNN_BENCHMARK: True

